import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/navigation/Navbar";
import Providers from "@/components/providers";
import { Server } from "@/components/server-state/Server";
import { QueryClient } from "@tanstack/react-query";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const queryClient = new QueryClient();

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={"h-full m-0"}>
			<body className="mx-auto px-4 max-w-5xl bg-white dark:bg-slate-950 text-slate-950 dark:text-white flex flex-col h-full">
				<Providers>
					<Navbar />

					<hr />

					{children}

					<hr />

					<Server />
				</Providers>
			</body>
		</html>
	);
}
